import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  docs: [
    "intro",
    "getting-started",
    {
      type: "category",
      label: "Connect SDK",
      link: { type: "doc", id: "connect/overview" },
      collapsed: false,
      items: [
        "connect/quickstart",
        "connect/origin-policy",
        "connect/webhooks-claim",
        "connect/webhooks-crawl",
        "connect/webhook-security",
        "connect/webhook-examples",
      ],
    },
    {
      type: "category",
      label: "REST API",
      link: { type: "doc", id: "api/overview" },
      collapsed: false,
      items: [
        "api/authentication",
        "api/pagination",
        "api/security",
        "api/ssh-keys",
        "api/gpg-keys",
        "api/date-ranges",
      ],
    },
  ],
  // Generated by docusaurus-plugin-openapi-docs at build time
  // (runs in `prebuild` / `prestart`). The plugin writes
  // `docs/api-reference/sidebar.ts`; we import it here.
  apiReference: requireSidebarOrEmpty("./docs/api-reference/sidebar.ts"),
  // Generated by scripts/clone-sdk-docs.sh at build time
  // (also runs in `prebuild` / `prestart`).
  sdk: requireSidebarOrEmpty("./docs/sdk/sidebar.ts"),
};

function requireSidebarOrEmpty(path: string) {
  try {
    return require(path);
  } catch {
    return [];
  }
}

export default sidebars;
